export const timezones = [
  { value: "Pacific/Baker", label: "(GMT-12:00) International Date Line West" },
  { value: "Pacific/Midway", label: "(GMT-11:00) Midway Island, Samoa" },
  { value: "Pacific/Honolulu", label: "(GMT-10:00) Hawaii" },
  { value: "America/Anchorage", label: "(GMT-09:00) Alaska" },
  {
    value: "America/Los_Angeles",
    label: "(GMT-08:00) Pacific Time (US & Canada)",
  },
  { value: "America/Denver", label: "(GMT-07:00) Mountain Time (US & Canada)" },
  { value: "America/Chicago", label: "(GMT-06:00) Central Time (US & Canada)" },
  {
    value: "America/New_York",
    label: "(GMT-05:00) Eastern Time (US & Canada)",
  },
  { value: "America/Halifax", label: "(GMT-04:00) Atlantic Time (Canada)" },
  {
    value: "America/Argentina/Buenos_Aires",
    label: "(GMT-03:00) Buenos Aires, Georgetown",
  },
  { value: "Atlantic/South_Georgia", label: "(GMT-02:00) Mid-Atlantic" },
  { value: "Atlantic/Azores", label: "(GMT-01:00) Azores, Cape Verde Is." },
  { value: "Europe/London", label: "(GMT+00:00) London, Dublin, Edinburgh" },
  { value: "Europe/Paris", label: "(GMT+01:00) Paris, Amsterdam, Berlin" },
  { value: "Africa/Cairo", label: "(GMT+02:00) Cairo, Jerusalem" },
  { value: "Europe/Moscow", label: "(GMT+03:00) Moscow, Baghdad" },
  { value: "Asia/Dubai", label: "(GMT+04:00) Abu Dhabi, Muscat" },
  { value: "Asia/Karachi", label: "(GMT+05:00) Islamabad, Karachi" },
  { value: "Asia/Calcutta", label: "(GMT+05:30) Chennai, Kolkata, Mumbai" },
  { value: "Asia/Dhaka", label: "(GMT+06:00) Dhaka" },
  { value: "Asia/Bangkok", label: "(GMT+07:00) Bangkok, Hanoi" },
  { value: "Asia/Singapore", label: "(GMT+08:00) Beijing, Singapore" },
  { value: "Asia/Tokyo", label: "(GMT+09:00) Tokyo, Seoul" },
  { value: "Australia/Sydney", label: "(GMT+10:00) Sydney, Melbourne" },
  { value: "Pacific/Guadalcanal", label: "(GMT+11:00) Solomon Is." },
  { value: "Pacific/Auckland", label: "(GMT+12:00) Auckland, Wellington" },
];
